name: Test and lint

on:
  schedule:
    - cron: "0 2 * * *"  # 2am UTC
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

env:
  FORCE_COLOR: 1
  PIP_DISABLE_PIP_VERSION_CHECK: 1

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  tests:
    name: Run tests

    # if 'schedule' was the trigger,
    # don't run it on contributors' forks
    if: >-
      github.repository == 'python/typing_extensions'
      || github.event_name != 'schedule'

    strategy:
      fail-fast: false
      matrix:
        # We try to test on the earliest available bugfix release of each
        # Python version, because typing sometimes changed between bugfix releases.
        # For available versions, see:
        # https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
        python-version:
          - "3.9"
          - "3.9.12"
          - "3.10"
          - "3.10.4"
          - "3.11"
          - "3.11.0"
          - "3.12"
          - "3.12.0"
          - "3.13"
          - "3.13.0"
          - "3.14"
          - "pypy3.9"
          - "pypy3.10"
          - "pypy3.11"

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          allow-prereleases: true

      - name: Install coverage
        run: |
          # Be wary that this does not install typing_extensions in the future
          pip install coverage
        
      - name: Test typing_extensions
        run: |
          # Be wary of running `pip install` here, since it becomes easy for us to
          # accidentally pick up typing_extensions as installed by a dependency
          cd src
          python --version  # just to make sure we're running the right one
          export COVERAGE_FILE=.coverage_${{ matrix.python-version }}
          # Run with coverage omit files that are executed in tempfiles
          coverage run --omit ann_module*,inspect* -m unittest test_typing_extensions.py

      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: .coverage_${{ matrix.python-version }}
          path: ./src/.coverage*
          include-hidden-files: true
          compression-level: 0 # no compression

      - name: Test CPython typing test suite
        # Test suite fails on PyPy even without typing_extensions
        if: ${{ !startsWith(matrix.python-version, 'pypy') }}
        run: |
          cd src
          # Run the typing test suite from CPython with typing_extensions installed,
          # because we monkeypatch typing under some circumstances.
          python -c 'import typing_extensions; import test.__main__' test_typing -v
 
  linting:
    name: Lint

    # no reason to run this as a cron job
    if: github.event_name != 'schedule'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3"
          cache: "pip"
          cache-dependency-path: "test-requirements.txt"
      - name: Install dependencies
        run: pip install -r test-requirements.txt
      - name: Lint implementation
        run: ruff check

  create-issue-on-failure:
    name: Create an issue if daily tests failed
    runs-on: ubuntu-latest

    needs: [tests]

    if: >-
        ${{
          github.repository == 'python/typing_extensions'
          && always()
          && github.event_name == 'schedule'
          && needs.tests.result == 'failure'
        }}

    permissions:
      issues: write

    steps:
      - uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.issues.create({
              owner: "python",
              repo: "typing_extensions",
              title: `Daily tests failed on ${new Date().toDateString()}`,
              body: "Runs listed here: https://github.com/python/typing_extensions/actions/workflows/ci.yml",
            })

  report-coverage:
    name: Report coverage

    runs-on: ubuntu-latest

    needs: [tests]

    if: ${{ always() }}

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3"
      - name: Download coverage artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: .coverage_*
          path: .
          # merge only when files are named differently
          merge-multiple: true
      - name: Install dependencies
        run: pip install coverage
      - name: Combine coverage results
        run: |
          # List the files to see what we have
          echo "Combining coverage files:"
          coverage combine --data-file=.coverage .coverage*
          # add -i to ignore parsed code of temp files.
          coverage report -i
          coverage xml -i

      - name: Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          # Alternatively use one file per python version
          filename: coverage.xml
          badge: true
          fail_below_min: false
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: '80 90'
  
      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: code-coverage-results.md
